#include<iostream>
//#include<exception>
using namespace std;

int main()

throw ("main");


try
{
catch (const char * msg)
{
cout<<msg<<endl;
}

}


